/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginNDashboard;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Student;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class dashboard extends javax.swing.JFrame {

    public void labelHover(JLabel lbl) {
        lbl.setForeground(Color.black);
        lbl.setFont(new java.awt.Font("Arial", 1, 40));
    }

    public void labelHoverOut(JLabel lbl) {
        lbl.setForeground(Color.black);
        lbl.setFont(new java.awt.Font("Arial", 0, 36));
    }

    private ArrayList<Student> students;

    public dashboard(ArrayList<Student> students) {
        initComponents();
        this.students = students;
        this.setLocationRelativeTo(null);
                viewPanel.setViewportView(new homeDashBoard());

    }

//    String[] columns = {"ID", "First Name", "Middle Name", "Last Name", "Course", "Year Level", "Status"};
//    private dashboard() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lbldashboard = new javax.swing.JLabel();
        viewPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 204, 51));

        lblHome.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblHome.setForeground(new java.awt.Color(0, 0, 0));
        lblHome.setText("HOME");
        lblHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });

        lbldashboard.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbldashboard.setForeground(new java.awt.Color(0, 0, 0));
        lbldashboard.setText("ACCOUNTS");
        lbldashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbldashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbldashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbldashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblHome))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lbldashboard)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(lblHome)
                .addGap(43, 43, 43)
                .addComponent(lbldashboard)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        viewPanel.setViewportView(new homeDashBoard());
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        labelHover(lblHome);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        labelHoverOut(lblHome);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lbldashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashboardMouseClicked
        viewPanel.setViewportView(new AccountPanel(students));

    }//GEN-LAST:event_lbldashboardMouseClicked

    private void lbldashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashboardMouseEntered
        labelHover(lbldashboard);
    }//GEN-LAST:event_lbldashboardMouseEntered

    private void lbldashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldashboardMouseExited
        labelHoverOut(lbldashboard);
    }//GEN-LAST:event_lbldashboardMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ArrayList<Student> students1 = new ArrayList<>(); // Initialize empty list
            new dashboard(students1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lbldashboard;
    private javax.swing.JScrollPane viewPanel;
    // End of variables declaration//GEN-END:variables
}
