/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginNDashboard;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Student;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    private ArrayList<Student> students;

    public dashboard(ArrayList<Student> students) {
        initComponents();
        this.students = students;
        this.setLocationRelativeTo(null);
    }
    
//    String[] columns = {"ID", "First Name", "Middle Name", "Last Name", "Course", "Year Level", "Status"};



//    private dashboard() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        btnLogout = new java.awt.Button();
        btnDelete = new java.awt.Button();
        btnUpdate = new java.awt.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        stuID = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        stuFirstname = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        stuMiddlename = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        stuLastname = new javax.swing.JTextPane();
        dropCourse = new javax.swing.JComboBox<>();
        dropYear = new javax.swing.JComboBox<>();
        dropStatus = new javax.swing.JComboBox<>();
        btnAdd = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stuTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        label1.setText("Student Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), " STUDENT FORM ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        btnLogout.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnLogout.setLabel("LOG OUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnDelete.setLabel("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnUpdate.setLabel("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        stuID.setBackground(new java.awt.Color(204, 204, 204));
        stuID.setForeground(new java.awt.Color(0, 0, 0));
        stuID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stuIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stuIDFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(stuID);

        stuFirstname.setBackground(new java.awt.Color(204, 204, 204));
        stuFirstname.setForeground(new java.awt.Color(0, 0, 0));
        stuFirstname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stuFirstnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stuFirstnameFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(stuFirstname);

        stuMiddlename.setBackground(new java.awt.Color(204, 204, 204));
        stuMiddlename.setForeground(new java.awt.Color(0, 0, 0));
        stuMiddlename.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stuMiddlenameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stuMiddlenameFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(stuMiddlename);

        stuLastname.setBackground(new java.awt.Color(204, 204, 204));
        stuLastname.setForeground(new java.awt.Color(0, 0, 0));
        stuLastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stuLastnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                stuLastnameFocusLost(evt);
            }
        });
        jScrollPane5.setViewportView(stuLastname);

        dropCourse.setBackground(new java.awt.Color(204, 204, 204));
        dropCourse.setForeground(new java.awt.Color(0, 0, 0));
        dropCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a course", "BSIT", "BSBA", "BSED Eng", "BSHM" }));
        dropCourse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dropCourseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dropCourseFocusLost(evt);
            }
        });
        dropCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropCourseActionPerformed(evt);
            }
        });

        dropYear.setBackground(new java.awt.Color(204, 204, 204));
        dropYear.setForeground(new java.awt.Color(0, 0, 0));
        dropYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a year", "1ST YEAR", "2ND YEAR", "3RD YEAR", "4TH YEAR" }));
        dropYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dropYearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dropYearFocusLost(evt);
            }
        });
        dropYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropYearActionPerformed(evt);
            }
        });

        dropStatus.setBackground(new java.awt.Color(204, 204, 204));
        dropStatus.setForeground(new java.awt.Color(0, 0, 0));
        dropStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a status", "ENROLLED", "UNENROLLED", "IRREGULAR", "DROPPED" }));
        dropStatus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dropStatusFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dropStatusFocusLost(evt);
            }
        });
        dropStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropStatusActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        btnAdd.setLabel("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("STATUS:");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("COURSE:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("YEAR:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("STUDENT ID:");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("FIRSTNAME:");

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MIDDLENAME:");

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("LASTNAME:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dropStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(dropCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(dropYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        stuTable.setBackground(new java.awt.Color(204, 204, 204));
        stuTable.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        stuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Name", "Course", "Year", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stuTable);

        jPanel4.setBackground(new java.awt.Color(0, 204, 51));

        txtSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.setText(" Search Data");
        txtSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you are going to exit", "CONFIRMATION", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }
        dispose();
        new Login(new JFrame(), true, students).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      // Get values from input fields
    String id = stuID.getText().trim();
    String firstName = stuFirstname.getText().trim();
    String lastName = stuLastname.getText().trim();
    String middleName = stuMiddlename.getText().trim();
    String course = (String) dropCourse.getSelectedItem();
    String yearLevel = (String) dropYear.getSelectedItem();
    String status = (String) dropStatus.getSelectedItem();

    // Validate inputs
    if (id.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || course == null || yearLevel == null || status == null) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields!", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Format full name as "Last, First Middle"
    String fullName = lastName + ", " + firstName + " " + middleName;

    // Create a new Student object and add it to the ArrayList
    students.add(new Student(id, firstName, lastName, middleName, course, yearLevel, status));

    // Get the table model and add a new row
    DefaultTableModel model = (DefaultTableModel) stuTable.getModel();
    model.addRow(new Object[]{id, fullName, course, yearLevel, status});

    // Show confirmation message
    JOptionPane.showMessageDialog(this, "Student added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    // Clear input fields
    stuID.setText("");
    stuFirstname.setText("");
    stuLastname.setText("");
    stuMiddlename.setText("");
    dropCourse.setSelectedIndex(0);
    dropYear.setSelectedIndex(0);
    dropStatus.setSelectedIndex(0);
    
   
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // Get the search query
    String searchQuery = txtSearch.getText().trim().toLowerCase();

    // Get the table model
    DefaultTableModel model = (DefaultTableModel) stuTable.getModel();
    
    // Clear existing rows in the table
    model.setRowCount(0);

    // Loop through the students list and find matches
    for (Student student : students) {
        String id = student.getId().toLowerCase();
        String fullName = (student.getLastName() + ", " + student.getFirstName() + " " + student.getMiddleName()).toLowerCase();
        String course = student.getCourse().toLowerCase();
        String yearLevel = student.getYearLevel().toLowerCase();
        String status = student.getStatus().toLowerCase();

        // Check if the search query matches any field
        if (id.contains(searchQuery) || fullName.contains(searchQuery) || course.contains(searchQuery) || yearLevel.contains(searchQuery) || status.contains(searchQuery)) {
            model.addRow(new Object[]{id, fullName, course, yearLevel, status});
        }
    }
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
         if (txtSearch.getText().equals(" Search Data")) {
            txtSearch.setText(null);
         }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        if (txtSearch.getText().isEmpty()) {
            txtSearch.setText(" Search Data");
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void dropCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropCourseActionPerformed

    private void dropYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropYearActionPerformed

    private void dropStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropStatusActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         // Get selected row index
    int selectedRow = stuTable.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student to update.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Get updated values from input fields
    String id = stuID.getText().trim();
    String firstName = stuFirstname.getText().trim();
    String lastName = stuLastname.getText().trim();
    String middleName = stuMiddlename.getText().trim();
    String course = (String) dropCourse.getSelectedItem();
    String yearLevel = (String) dropYear.getSelectedItem();
    String status = (String) dropStatus.getSelectedItem();

    // Validate inputs
    if (id.isEmpty() || firstName.isEmpty() || lastName.isEmpty() || course == null || yearLevel == null || status == null) {
        JOptionPane.showMessageDialog(this, "Please fill in all required fields!", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Format full name as "Last, First Middle"
    String fullName = lastName + ", " + firstName + " " + middleName;

    // Update the ArrayList (students)
    Student updatedStudent = new Student(id, firstName, lastName, middleName, course, yearLevel, status);
    students.set(selectedRow, updatedStudent);

    // Update JTable model
    DefaultTableModel model = (DefaultTableModel) stuTable.getModel();
    model.setValueAt(id, selectedRow, 0);
    model.setValueAt(fullName, selectedRow, 1);
    model.setValueAt(course, selectedRow, 2);
    model.setValueAt(yearLevel, selectedRow, 3);
    model.setValueAt(status, selectedRow, 4);

    // Show confirmation message
    JOptionPane.showMessageDialog(this, "Student data updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    // Clear input fields
    stuID.setText("");
    stuFirstname.setText("");
    stuLastname.setText("");
    stuMiddlename.setText("");
    dropCourse.setSelectedIndex(0);
    dropYear.setSelectedIndex(0);
    dropStatus.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get selected row index
    int selectedRow = stuTable.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a student to delete.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Confirm before deleting
    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this student?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        // Remove from ArrayList
        students.remove(selectedRow);

        // Remove from JTable model
        DefaultTableModel model = (DefaultTableModel) stuTable.getModel();
        model.removeRow(selectedRow);

        // Show confirmation message
        JOptionPane.showMessageDialog(this, "Student deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void dropCourseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropCourseFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dropCourseFocusGained

    private void dropCourseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropCourseFocusLost
         if (dropCourse.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select a Course!", "Input Error", JOptionPane.ERROR_MESSAGE);
        dropCourse.requestFocus();
    }
    }//GEN-LAST:event_dropCourseFocusLost

    private void dropYearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropYearFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dropYearFocusGained

    private void dropYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropYearFocusLost
        if (dropYear.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select a Year Level!", "Input Error", JOptionPane.ERROR_MESSAGE);
        dropYear.requestFocus();
    }
    }//GEN-LAST:event_dropYearFocusLost

    private void dropStatusFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropStatusFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_dropStatusFocusGained

    private void dropStatusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dropStatusFocusLost
      if (dropStatus.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Please select a Status!", "Input Error", JOptionPane.ERROR_MESSAGE);
        dropStatus.requestFocus();
    }
    }//GEN-LAST:event_dropStatusFocusLost

    private void stuIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuIDFocusGained
         if (stuID.getText().equals("Student ID")) {
            stuID.setText(null);
        }
    }//GEN-LAST:event_stuIDFocusGained

    private void stuIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuIDFocusLost
        if (stuID.getText().isEmpty()) {
            stuID.setText("Student ID");
        }
    }//GEN-LAST:event_stuIDFocusLost

    private void stuFirstnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuFirstnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stuFirstnameFocusGained

    private void stuFirstnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuFirstnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_stuFirstnameFocusLost

    private void stuMiddlenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuMiddlenameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stuMiddlenameFocusGained

    private void stuMiddlenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuMiddlenameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_stuMiddlenameFocusLost

    private void stuLastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuLastnameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_stuLastnameFocusGained

    private void stuLastnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stuLastnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_stuLastnameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            ArrayList<Student> students1 = new ArrayList<>(); // Initialize empty list
            new dashboard(students1).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAdd;
    private java.awt.Button btnDelete;
    private java.awt.Button btnLogout;
    private java.awt.Button btnUpdate;
    private javax.swing.JComboBox<String> dropCourse;
    private javax.swing.JComboBox<String> dropStatus;
    private javax.swing.JComboBox<String> dropYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Label label1;
    private javax.swing.JTextPane stuFirstname;
    private javax.swing.JTextPane stuID;
    private javax.swing.JTextPane stuLastname;
    private javax.swing.JTextPane stuMiddlename;
    private javax.swing.JTable stuTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
